name: "test: formatting queries"
on: # rebuild any PRs and {master, main} branch changes
    pull_request:
    push:
        branches:
            - master
            - main

jobs:
    test: # make sure the action works on a clean machine without building
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2.0.0

            - name: Install zetasql
              run: |
                wget https://github.com/Matts966/zetasql-formatter/releases/latest/download/zetasql-formatter_linux_x86_64.zip
                sudo unzip zetasql-formatter_linux_x86_64.zip -d /usr/local/bin
                rm zetasql-formatter_linux_x86_64.zip

            - name: Auto-formatting queries
              id: AutoFormat
              uses: ./
              with:
                github_token: ${{ secrets.github_token }}
                auto_fix: "true"
                git_name: "[TEST] BigQuery AutoFormatter"
                git_email: "test+test@example.com"
                commit_message: "[TEST] Auto-format queries"